title = "AkarinWrt"
baseURL = "https://akarinwrt.github.io"
languageCode = "zh"
theme = ["gohugo-theme-ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "zh"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[menu]
  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 0
  [[menu.main]]
    name = "下载"
    url = "/downloads/"
    weight = 1

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "github"
url = "https://github.com/AkarinWrt"
